### ISSUE TITLE
Migrate to github.com/shurcooL/go/generated

### ISSUE THREAD

**Issue by bradleyfalzon** [gopherci/isFileGenerated#1]
Migrate to use https://godoc.org/github.com/shurcooL/go/generated

**Comment by dmitshur** [comment]
I'll send a PR to resolve this issue soon. **Edit:** Sent PR #2.

**Comment by dmitshur** [comment]
Also, this `staticcheck` output is mildly amusing in this context. :)

```
main.go:17:20: analysis.IsFileGenerated is deprecated: Use generated.ParseFile instead, which is more well defined because it implements a specification.  (SA1019)
```

(/cc @dominikh FYI; your tool is mentioned.)

**Comment by bradleyfalzon** [comment]
The PR looks good, thanks @shurcooL, a minor change to my integration tests to use the new syntax so it's made GopherCI better, extra thanks for that. Just updating production now, will close the issue once done.

**Comment by bradleyfalzon** [comment]
Thanks again!
