### ISSUE TITLE
package go/generated has moved to a new import path

### ISSUE THREAD

**Issue by dmitshur** [gopherci/isFileGenerated#3]
Hello @bradleyfalzon.

According to godoc.org, this package is the only [importer](https://godoc.org/github.com/shurcooL/go/generated?importers) of `github.com/shurcooL/go/generated`. That package has moved. Its new import path is [`dmitri.shuralyov.com/go/generated`](https://godoc.org/dmitri.shuralyov.com/go/generated).

If it'd helpful to you, I'm happy to send a PR to make the change. I wanted to open an issue first and see if you'd be willing to accept the PR.

Thanks!

**Comment by bradleyfalzon** [comment]
Hi @dmitshur, a PR would be the quickest way if that's possible?

**Comment by dmitshur** [comment]
Sure, sent PR #4!

**Comment by bradleyfalzon** [comment]
Thanks mate, merged!
